---
# tasks file for docker
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - container-selinux
      - yum-utils
      - device-mapper-persistent-data
    state: present

- name: Add Docker repository
  ansible.builtin.dnf:
    name: https://download.docker.com/linux/centos/docker-ce.repo
    state: present

- name: Install Docker package
  ansible.builtin.dnf:
    name: docker-ce
    state: present

- name: Start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes