name: Git Diff
run-name: Git Diff
on: [push]
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true # to only include folders in the output
          format: newline # either json, csv or newline
      - name: Echo
        run: for $i in ${{ steps.get_changed.outputs.changed }}; echo $i; done
