name: Get Diff
run-name: Get Diff
on: [push]
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jitterbit/get-changed-files@v1
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "${changed_file}."
        done