#TODO: Debug and add appropriate inputs
# name: Build and push Docker image to GCR

# on:
#   push:
#     branches:
#       - main

# env:
#   IMAGE_NAME: gcr.io/<PROJECT_ID>/<IMAGE_NAME>

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0.3.0
#         with:
#           version: '333.0.0'
#           service_account_key: ${{ secrets.GCLOUD_AUTH }}

#       - name: Configure Docker CLI
#         uses: docker/setup-docker@v1

#       - name: Build and tag Docker image
#         run: |
#           docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest -f containerfiles/Dockerfile .

#       - name: Authenticate with Google Cloud Container Registry
#         uses: google-github-actions/setup-gcloud@v0.3.0
#         with:
#           version: '333.0.0'
#           service_account_key: ${{ secrets.GCLOUD_AUTH }}
#       - run: gcloud auth configure-docker

#       - name: Push Docker image to GCR
#         run: |
#           docker push $IMAGE_NAME:${{ github.sha }}
#           docker push $IMAGE_NAME:latest