name: Git Dir
run-name: Git Dir
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - test
        - prod
        default: "dev"
      working_dir:
        type: string
        description: Working resource dir to run workflow from (eg- ec2)
        default: "ec2"
jobs:
  vars:
    runs-on: ubuntu-latest
    
    steps:
    - name: set env var long name
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
          echo "ENV=development" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
          echo "ENV=staging" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
          echo "ENV=production" >> $GITHUB_ENV
        else
          echo "ENV=development" >> $GITHUB_ENV
        fi
    - name: Checkout
      uses: actions/checkout@v3

    - name: Construct Run Path
      run: echo "/modules/$ENV/${{ github.event.inputs.working_dir}}" >> $GITHUB_ENV

    - name: checkout
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --report