name: Git Dir
run-name: Git Dir
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - test
        - prod
        default: "dev"
      product_dir:
        type: string
        description: Product dir to run workflow from (eg- terraform)
        default: "terraform"
      working_dir:
        type: string
        description: Working resource dir to run workflow from (eg- ec2)
        default: "ec2"
jobs:
  vars:
    runs-on: ubuntu-latest
    
    steps:
    - name: validate vars      
      run: echo "${{ github.event.inputs.environment}}/${{ github.event.inputs.product_dir}}/${{ github.event.inputs.working_dir}}"
    - name: set env var long name
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
          echo "development" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
          echo "staging" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
          echo "production" >> $GITHUB_ENV
        else
          echo "development" >> $GITHUB_ENV
    - name: output env var
      run: echo $GITHUB_ENV
