name: TFLint
run-name: TFLint
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - test
        - prod
        default: "dev"
      working_dir:
        type: string
        description: Working resource dir to run workflow from (eg- ec2)
        default: "ec2"

jobs:
  tflint:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      # Authentication
      - name: git config
        run: |
          git config --global user.name $username
          git config --global user.email $email
        env:
          username: ${{ secrets.username }}
          email: ${{ secrets.email }}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH }}
      
      #Setup Env
      - name: Set Environment Var
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "ENV=development" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          else
            echo "ENV=development" >> $GITHUB_ENV
          fi
      - name: Construct Run Path
        run: echo "modules/$ENV/${{ github.event.inputs.working_dir}}"
      - name: Change working dir
        run: |
          cd modules/$ENV/${{ github.event.inputs.working_dir}}

      # Execute
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1

      # Cleanup Run
      - name: Set Origin URL
        run: git remote set-url origin $ssh_url
        env:
          ssh_url: ${{ secrets.ssh_url }}
      - name: Check Changes
        run: git status
      - name: Stage Changes
        run: git add --all
      - name: Commit Changes
        run: git commit -m "Auto linting TF files"
      - name: Fetch Origin
        run: git fetch origin main
      - name: Push Changes to Origin
        run: git push origin HEAD:main
