name: TFLint
run-name: TFLint
on:
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest
    name: TFLint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
      
      #Need cd folder steps here to use validate
      # - name: Terraform Init
      #   id: init
      #   run: terraform init

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color