name: TFLint
run-name: TFLint
on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - test
        - prod
        default: "dev"
      working_dir:
        type: string
        description: Working resource dir to run workflow from (eg- ec2)
        default: "gcp-compute-vm"

jobs:
  TFlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Environment
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
          echo "ENV=development" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
          echo "ENV=staging" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
          echo "ENV=production" >> $GITHUB_ENV
        else
          echo "ENV=development" >> $GITHUB_ENV
        fi

    - name: Set Running Dir
      run: |
        cd terraform/$ENV/${{ github.event.inputs.working_dir}}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    # https://terraform-docs.io/how-to/github-action/
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        output-file: README.md
        output-method: inject
        git-push: "true"